training:
  num_clients: 3
  num_rounds: 3
  learning_rate: 0.01
  threshold: 0.000001

privacy:
  epsilon: 8.0
  delta: 1e-5
  noise_scale: 0.5

model:
  input_size: 784
  hidden_size: 128
  output_size: 10